### ISSUE TITLE
Add this to Shields.io

### ISSUE THREAD

**Issue by patricksamson** [geekpradd/Package-Control-Badges#2]
Hi!
Would you consider adding this to the [Shields.io project](https://github.com/badges/shields)?
They support quite a few badge providers, but Package Control is not one of them.

**Comment by geekpradd** [comment]
Yes, I'd love to!
Can you provide me some information regarding how to do so?

**Comment by patricksamson** [comment]
I went ahead and made a PR : [linky](https://github.com/badges/shields/pull/582)

**Comment by patricksamson** [comment]
It has been merged on their end, see this badge for Package Control : [![Package Control](https://img.shields.io/packagecontrol/dd/Package%20Control.svg)](https://packagecontrol.io/packages/Package%20Control)

**Comment by geekpradd** [comment]
So this repo is obsolete now. Well, atleast I won't have to maintain this project anymore.

**Comment by aristidesfl** [comment]
Hmm I'm missing something. What do I need to change to have the number of downloads? I obviously don't have 567k/month 😅
